kkmadb/urls.py
from django.conf.urls import url
from django.contrib import admin
from kkma import views

urlpatterns = [
    url(r'^add-example/', views.AddExample.as_view()),
    url(r'^add-batch-example/', views.AddBatchExample.as_view()),
    url(r'', admin.site.urls),
]

kkma/models.py
# -*- coding: UTF-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils.html import format_html, mark_safe

from django.db.models import F

import re


class Phrase(models.Model):
    phrase = models.CharField(max_length=255, db_index=True)
    count = models.IntegerField(default=0, verbose_name='Total Count')
    
    class Meta:
        ordering = ('-count',)
    
    def __unicode__(self):
        return self.phrase


class Example(models.Model):
    CATEGORY_CHOICES = (
        ('처소', '처소'),
		('추상 처소', '추상 처소'),
        ('출발점', '출발점'),
        ('출처', '출처'),
        ('근거', '근거'),
        ('비교의 기준', '비교의 기준'),
        ('주체임', '주체임'),
        ('기타', '기타'),
    )
    morpheme = models.CharField(verbose_name='형태소', max_length=255, db_index=True,
                                help_text='Keyword')  # 서 - 에서 Column C filename
    used_in = models.CharField(verbose_name='사용역', max_length=255, db_index=True,
                                help_text='Source of example')   # Column G sheet name     
    content = models.TextField(verbose_name='용례', null=True, blank=True)    # Column B

    prefix = models.CharField(verbose_name='선행요소', max_length=400, null=True, blank=True)   # Column E
    suffix = models.CharField(verbose_name='후행요소', max_length=400, null=True, blank=True)   # Column F
    category = models.CharField(verbose_name='의미', max_length=50, db_index=True,
                                choices=CATEGORY_CHOICES, null=True, blank=True) # D
    modified_on = models.DateTimeField(null=True, blank=True, auto_now=True)
    
    phrases = models.ManyToManyField(Phrase, related_name='examples')
                                
    '''class Meta:
        ordering = ['morpheme', ]'''
        
    def __unicode__(self):
        return self.content
    

kkma/forms.py
from django import forms
from django.conf import settings

from .models import Example


class ExampleImportForm(forms.ModelForm):
    class Meta:
        model = Example
        fields = ['morpheme', 'content', 'used_in', 'prefix', 'suffix', 'category']
                  

class FlashcardForm(forms.ModelForm):
    category = forms.ChoiceField(widget=forms.RadioSelect)
    
    class Meta:
        model = Example
        fields = ['category', 'prefix', 'suffix',]
        widgets = {
            'prefix': forms.TextInput(attrs={'class': 'form-control'}),
            'suffix': forms.TextInput(attrs={'class': 'form-control'}),
        }
        
    def __init__(self, *args, **kwargs):
        super(FlashcardForm, self).__init__(*args, **kwargs)
        categories = ((None, '0. Not set'), )
        for index, option in enumerate(Example.CATEGORY_CHOICES):
            new_option = ((option[0], str(index + 1) + '. ' + option[1]), )
            categories += new_option
        self.fields['category'].choices = categories

kkma/views.py
from django.shortcuts import render
import json

from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (CreateView, FormView, ListView,
                                  UpdateView, DetailView, View)
                                  

from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .forms import ExampleImportForm
from .models import Example
from django.core.serializers.json import DjangoJSONEncoder


class APIResponse(JsonResponse):
    def __init__(self, request, status=200, context=None,
                 encoder=DjangoJSONEncoder, **kwargs):
        self.request = request
        data = self._get_response_data(context, status)
        super(APIResponse, self).__init__(data=data, encoder=encoder,
                                          status=status, **kwargs)

    def _get_response_data(self, context, status):
        request = self.request
        return context


class AddExample(CreateView):
    success_url = '/'
    model = Example
    form_class = ExampleImportForm
    response_class = APIResponse
    
    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        return super(AddExample, self).dispatch(request, *args, **kwargs)
        
    def form_valid(self, form):
        example = form.save(commit=False)
        '''query = Example.objects.filter(
            word_type=example.word_type, ws_type=example.ws_type,
            morpheme=example.morpheme, content=example.content
        )
        if len(query) > 0:
            return JsonResponse({'success': False, 'reason': 'Existed'})
        '''
        example.save()
        return JsonResponse({'success': True})
        
    def form_invalid(self, form):
        print form.errors
        return JsonResponse({'success': False})
        
    def get(self, request):
        return JsonResponse({'success': True, 'field': [
            'word_type', 'ws_type', 'morpheme',
            'index', 'content', 'detail', 'field_id',
            'part_id', 'sent_id'
        ]})
        
class AddBatchExample(View):
    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        return super(AddBatchExample, self).dispatch(request, *args, **kwargs)
        

    def post(self, request):
        data = request.POST.get('data', '[]')
        try:
            data = json.loads(data)
            Example.objects.bulk_create([Example(**ex) for ex in data])
            return JsonResponse({'success': True})
        except:
            return JsonResponse({'success': False})

kkma/templates/kkma/example/change_list.html
{% extends "admin/change_list.html" %}
{% load i18n %}

{% block object-tools-items %}
  <a class="btn" href="flash-card/{{ cl.get_query_string }}" class="flash-card-launch">{% trans "Lauch Flash card" %}</a>
  <a class="btn" href="export/{{ cl.get_query_string }}" class="export_link">{% trans "Export" %}</a>
  {{ block.super }}
{% endblock %}

kkma/templates/kkma/example/flash_card.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>

        <title>Flashcard editor</title>

        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static "flashcard.css" %}"/>

        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="flashcard container-fluid">
            <form action="" class="example-form" method="POST">
                <div class="text-right return-link">
                    <!--label class="pull-left"><input type="checkbox" name="random"/> Auto jump to random example when selected</label-->
                    
                    <a href="{% url 'admin:index' %}">Home</a> / <a href="{% url 'admin:app_list' 'kkma' %}">kkma</a> / <a href="{% url 'admin:kkma_example_changelist' %}?{{filter_link}}">Example</a>
                </div>
                {% if object %}
                <div class="content">
                    {{object.content|safe}}
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label for="id_prefix">Prefix</label>
                            {{form.prefix}} 
                        </div>
                        <div class="form-group">
                            <label for="id_suffix">Suffix</label>
                            {{form.suffix}} 
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-content">
                            {% csrf_token %}
                            <input type="hidden" name="pk" value="{{object.pk}}" />
                            {{form.category}} 
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="translate">
                            
                        </div>
                    </div>
                </div>
            </form>
            {% else %}
            <div class="content text-center">
                The End!!!
            </div>
            {% endif %}
            <div class="footer">
                <div class="row">
                    <div class="col-xs-3">
                        
                    </div>
                    <div class="col-xs-6">
                        {% if object %}
                            {{ index|add:1 }} / {{ total }}
                        {% endif %}
                    </div>
                    <div class="col-xs-3">
                        {% if next_link %}
                        <a class="btn-next" href="?{{next_link}}" title="Press [Enter] or [Right Arrow]">Random next &gt;&gt;</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.3/js.cookie.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script>
            $('.flashcard form input').change(function(){
                $('.flashcard form').submit();
            });

            $(document).on('keydown', function( e ) {
                if (e.keyCode == 13 || e.keyCode == 39) {
                    $('.btn-next').get(0).click();
                }

                if (e.keyCode == 37) {
                    $('.btn-prev').get(0).click();
                }

                var number = null;
                if (e.keyCode >= 48 && e.keyCode <= 57) {
                    number = e.keyCode - 48;
                }

                if (e.keyCode >= 96 && e.keyCode <= 105) {
                    number = e.keyCode - 96;
                }

                if (number !== null) {
                    var $selectedopt = $('#id_category_' + number);
                    if ($selectedopt.length > 0) {
                        $selectedopt.click();
                    }
                }
            });
            
            var is_random = Cookies.get('random');
            $('input[name="random"]').prop('checked', is_random==='yes');
            $('input[name="random"]').click(function() {
                Cookies.set('random', $(this).prop('checked') ? 'yes' : 'no', { expires: 7, path: '/'});
            });
            
            // Translate
            {% if object %}
            var translate = {};
            $.get('{% url 'admin:kkma_example_translate' %}?query='+$('.content').text().trim(), function(data) {
                translate = data;
                var nodes = $(".content").get(0).childNodes;
                var wrapedHtml = '';
                for (var i=0, l=nodes.length; i < l; i++) {
                    var node = nodes[i];
                    if (node.nodeType === 3) {  // Textnode
                        var words = node.data.trim().split(' ');
                        for (var j=0; j<words.length; j++) {
                            if (translate[words[j]]) {
                                wrapedHtml += '<span class="highlight">' + words[j] + '</span> ';
                            } else {
                                wrapedHtml += words[j] + ' ';
                            }
                        }
                    } else if (node.nodeType === 1) {
                        node.className = 'highlight';
                        wrapedHtml += node.outerHTML + ' ';
                    }
                }
                $(".content").html(wrapedHtml);
                $('.translate').html('Click highlighted word to see translate');
            });
            
            $('.content').on('click', '.highlight', function() {
                var text = $(this).text();
                if (translate[text].length > 0) {
                    $('.translate').html('<div class="text-center"><a href="http://vndic.naver.com/search.nhn?query='+text+'" target="_blank">'+text+'</a></div>' + translate[text].join(''));
                } else {
                    $('.translate').html('<div class="text-center"><a href="http://vndic.naver.com/search.nhn?query='+text+'" target="_blank">'+text+'</a></div');
                }
            });
            {% endif %}
            
        </script>
    </body>
</html>